import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Background from "./components/background/Background";
import Header from "./components/header/Header";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Flower Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box>
          <Header />
          <Background />
          {children}
        </Box>
      </body>
    </html>
  );
}
